// Phase 0.5 — consultation priorities: computation → session state → hf2
// Consultation Summary → email payload projection.
//
// This does NOT grep for behavior. It EXTRACTS the real showProfileScreen(),
// renderResultsTrialFocus(), renderHf2Priorities(), L(), escapeHtml() and the
// payload's priorities projection from index.html and EXECUTES them against a
// recording DOM shim — the same extract-and-execute pattern as
// tests/session_safety_check.mjs and tests/data_error_recovery_check.mjs.
//
// The Sleep Brief pin: tests/fixtures/sleep_brief_baseline_572d405.json was
// generated by executing the PRE-0.5 showProfileScreen (commit 572d405, the
// baseline main this phase branched from) against the fixtures below. The
// current tree must still produce byte-identical Sleep Brief output — that is
// what "0.5 does not change the Sleep Brief" means, made executable. Do NOT
// regenerate that file from a post-0.5 tree; a regenerated pin certifies
// whatever the change produced, which is the vacuity this suite exists to
// prevent.
//
// Fixture design (derived by executing the real engine at 572d405):
//   C — sorted top-3 is a DIFFERENT SET from its insertion top-3, so it kills
//       "sort removed", "sort reversed" and "slice before sort" at once. It
//       also carries a real tie (Motion control 90 vs Consistent support 90)
//       resolved by stable-sort insertion order.
//   E, F — different populated orders; F's three are all kind:'compare'.
//   A — the classic hot side sleeper.
//   I — a tie at rank 1–2 (two 100s), pinning tie stability.
//   B — exactly TWO priorities; H — exactly ONE. The engine produces 1–3, not
//       always three; both surfaces must render the engine's count, never pad.
// A "sorted order == insertion order" fixture is deliberately ABSENT from the
// order tests: on such a fixture every order mutation survives.
//
// Run: node tests/consultation_priorities_check.mjs

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const html = readFileSync(join(root, "index.html"), "utf8");
const BASELINE = JSON.parse(readFileSync(
  join(root, "tests", "fixtures", "sleep_brief_baseline_572d405.json"), "utf8"));

let passed = 0, failed = 0;
function check(label, cond) {
  if (cond) { passed++; console.log(`  [ok] ${label}`); }
  else { failed++; console.log(`  [FAIL] ${label}`); }
}
function section(name) { console.log(`\n-- ${name} --`); }
function grab(re, what) {
  const m = html.match(re);
  check(`extracted ${what}`, !!m);
  return m ? m[0] : "";
}

// ---------- extractions ------------------------------------------------------
section("extraction");
const PROFILE_FN = grab(/function showProfileScreen\(\) \{[\s\S]*?\r?\n    \}\r?\n/, "showProfileScreen()");
const TRIAL_FN = grab(/function renderResultsTrialFocus\(\)\s*\{[\s\S]*?\n    \}/, "renderResultsTrialFocus()");
const HF2_FN = grab(/function renderHf2Priorities\(\)\s*\{[\s\S]*?\n    \}/, "renderHf2Priorities()");
const L_FN = grab(/function L\(obj\) \{[\s\S]*?\n    \}/, "L()");
const ESCAPE_FN = grab(/function escapeHtml\([\s\S]*?\n    \}/, "escapeHtml()");
const PROJECTION = grab(
  /priorities: \(Array\.isArray\(analytics\.trialFocus\) \? analytics\.trialFocus : \[\]\)[\s\S]*?\.filter\(function\(p\) \{ return p\.name; \}\),/,
  "the payload priorities projection");

// ---------- fixtures (identical to the baseline generator's) ----------------
const FIXTURES = {
  C: { sleep_position: "combo", temperature: "cold", firmness: 2,
       partner_sleep: "family", partner_disturbance: "sometimes",
       sleep_issues: ["hip_pain", "sagging"], health_conditions: ["reflux"],
       body_type: "plus", mattress_size: "queen" },
  E: { sleep_position: "stomach", temperature: "cold", firmness: 8,
       partner_sleep: "partner", partner_disturbance: "yes_often",
       sleep_issues: ["sagging"], health_conditions: [], mattress_size: "king" },
  F: { sleep_position: "combo", temperature: "opposite", firmness: 2,
       partner_sleep: "partner", partner_disturbance: "no",
       sleep_issues: [], health_conditions: ["allergies"], mattress_size: "full" },
  A: { sleep_position: "side", temperature: "hot", firmness: 4,
       partner_sleep: "partner", partner_disturbance: "yes_often",
       sleep_issues: ["back_pain", "hot"], health_conditions: ["snoring"], mattress_size: "queen" },
  I: { sleep_position: "back", temperature: "hot", firmness: 6,
       partner_sleep: "partner", partner_disturbance: "sometimes",
       sleep_issues: ["back_pain"], health_conditions: ["snoring"],
       body_type: "plus", mattress_size: "twin" },
  B: { sleep_position: "back", temperature: "comfortable", firmness: 8,
       partner_sleep: "solo", sleep_issues: ["none"], health_conditions: ["none"],
       mattress_size: "twin_xl" },
  H: {},
};
const ORDER_FIXTURES = ["C", "E", "F", "A", "I"];   // never B/H — bounds only

// ---------- harness ----------------------------------------------------------
function makeDoc() {
  const els = new Map();
  const make = (id) => ({
    id, innerHTML: "", textContent: "", style: {},
    classList: { add() {}, remove() {}, contains: () => false },
    setAttribute() {}, getAttribute: () => null, focus() {},
  });
  const doc = {
    getElementById: (id) => {
      if (!els.has(id)) els.set(id, make(id));
      return els.get(id);
    },
    querySelector: () => null, querySelectorAll: () => [],
  };
  return { els, doc };
}

// Executes the real profile render (and the results derivative) for one
// fixture in one language. Returns the recorded DOM plus the analytics state.
function runProfile(fixture, lang) {
  const { els, doc } = makeDoc();
  const analytics = { trialFocus: [], log() {} };
  const out = {};
  new Function("document", "window", "answers", "currentLang", "analytics", "out",
    `"use strict";
    function t(k) { return k; }
    function showScreen() {}
    ${ESCAPE_FN}
    ${L_FN}
    ${PROFILE_FN}
    ${TRIAL_FN}
    out.run = function() { showProfileScreen(); renderResultsTrialFocus(); };
    `)(doc, {}, JSON.parse(JSON.stringify(fixture)), lang, analytics, out);
  out.run();
  return { els, analytics };
}

function parseBriefList(innerHTML) {
  return [...innerHTML.matchAll(/<li class="noct-profile-priority-row">([\s\S]*?)<\/li>/g)]
    .map((m) => ({
      title: (m[1].match(/priority-title">([\s\S]*?)<\/div>/) || [, ""])[1],
      desc: (m[1].match(/priority-desc">([\s\S]*?)<\/div>/) || [, ""])[1],
      tagClass: (m[1].match(/priority-tag (tag-[a-z]+)">/) || [, ""])[1],
      tag: (m[1].match(/priority-tag tag-[a-z]+">([\s\S]*?)<\/div>/) || [, ""])[1],
      test: (m[1].match(/priority-test"><strong>[\s\S]*?<\/strong>([\s\S]*?)<\/div>$/) || [, ""])[1],
    }));
}

// Executes the real hf2 renderer against a stored trialFocus state.
function runHf2(trialFocus, lang) {
  const { els, doc } = makeDoc();
  const analytics = { trialFocus };
  const out = {};
  new Function("document", "currentLang", "analytics", "out",
    `"use strict";
    ${ESCAPE_FN}
    ${L_FN}
    ${HF2_FN}
    out.run = function() { renderHf2Priorities(); };
    `)(doc, lang, analytics, out);
  out.run();
  return {
    section: els.get("hf2PrioritiesSection"),
    list: els.get("hf2Priorities"),
    names: [...els.get("hf2Priorities").innerHTML.matchAll(/<strong>([\s\S]*?)<\/strong>/g)]
      .map((m) => m[1]),
  };
}

// Executes the real payload projection expression, exactly as extracted.
function runProjection(trialFocus, lang) {
  return new Function("analytics", "currentLang",
    `"use strict";
    return { ${PROJECTION} }.priorities;`)({ trialFocus }, lang);
}

// ===========================================================================
// 1. COMPUTATION AND ORDER — the engine's output, per fixture, per language
// ===========================================================================
section("computation: engine order, count and tie stability");
for (const f of ORDER_FIXTURES) {
  for (const lang of ["en", "es"]) {
    const { analytics } = runProfile(FIXTURES[f], lang);
    const got = analytics.trialFocus.map((t) => t[lang]);
    const want = BASELINE[f][lang].trialFocus.map((t) => t[lang]);
    check(`[${f}/${lang}] engine order pinned: ${want.join(" > ")}`,
      JSON.stringify(got) === JSON.stringify(want));
  }
}
{
  const b = runProfile(FIXTURES.B, "en").analytics.trialFocus;
  const h = runProfile(FIXTURES.H, "en").analytics.trialFocus;
  check("the engine produces TWO priorities for fixture B — never padded to three",
    b.length === 2);
  check("...and ONE for fixture H", h.length === 1);
}

// ===========================================================================
// 2. SLEEP BRIEF UNCHANGED — executed output vs the 572d405 pin
// ===========================================================================
section("Sleep Brief output is byte-identical to the 572d405 pin");
for (const f of Object.keys(FIXTURES)) {
  for (const lang of ["en", "es"]) {
    const { els, analytics } = runProfile(FIXTURES[f], lang);
    const pin = BASELINE[f][lang];
    const got = parseBriefList(els.get("profilePriorities").innerHTML);
    check(`[${f}/${lang}] priority rows (title/desc/tag/tagClass/test) unchanged`,
      JSON.stringify(got) === JSON.stringify(pin.priorities));
    check(`[${f}/${lang}] row count unchanged`, got.length === pin.priorities.length);
    check(`[${f}/${lang}] summary line unchanged`,
      els.get("profileSummary").textContent === pin.summary);
    check(`[${f}/${lang}] heading and intro unchanged`,
      els.get("profilePrioritiesHeading").textContent === pin.heading
      && els.get("profilePrioritiesIntro").textContent === pin.intro);
    check(`[${f}/${lang}] profileBriefByLang unchanged (both languages)`,
      JSON.stringify(analytics.profileBriefByLang) === JSON.stringify(pin.briefByLang));
    check(`[${f}/${lang}] results trial-focus derivative unchanged`,
      els.get("resultsTrialFocus").innerHTML === pin.resultsTrialFocus);
    // The pin's trialFocus carried only {en, es}; the widened state must still
    // agree on those names, in the same positions.
    check(`[${f}/${lang}] trialFocus name pairs unchanged`,
      JSON.stringify(analytics.trialFocus.map((t) => ({ en: t.en, es: t.es })))
      === JSON.stringify(pin.trialFocus));
  }
}

// ===========================================================================
// 3. THE WIDENED STATE
// ===========================================================================
section("the widened session state: bilingual prose, nothing internal");
{
  const { analytics } = runProfile(FIXTURES.C, "en");
  const KEYS = ["en", "es", "test", "why"];
  analytics.trialFocus.forEach((item, i) => {
    check(`element ${i}: key set is exactly en/es/why/test — no score, kind or rank`,
      JSON.stringify(Object.keys(item).sort()) === JSON.stringify(KEYS));
    check(`element ${i}: why and test are bilingual pairs`,
      typeof item.why.en === "string" && item.why.en.length > 0
      && typeof item.why.es === "string" && item.why.es.length > 0
      && typeof item.test.en === "string" && item.test.en.length > 0
      && typeof item.test.es === "string" && item.test.es.length > 0);
    check(`element ${i}: the ES prose is actually Spanish, not a copied EN string`,
      item.why.en !== item.why.es && item.test.en !== item.test.es);
  });
  // Language-independence of the STORE: computing under ES yields the same
  // bilingual state as computing under EN.
  const esState = runProfile(FIXTURES.C, "es").analytics.trialFocus;
  check("the stored state is identical whichever language computed it",
    JSON.stringify(esState) === JSON.stringify(analytics.trialFocus));
}

// ===========================================================================
// 4. THE CONSULTATION SUMMARY RENDER
// ===========================================================================
section("hf2: ordered render from stored state, both languages, no recompute");
{
  const state = runProfile(FIXTURES.C, "en").analytics.trialFocus;
  const en = runHf2(state, "en");
  check("visible with valid state", en.section.style.display === "");
  check("renders every stored priority, in order",
    JSON.stringify(en.names) === JSON.stringify(state.map((t) => t.en)));
  check("the renderer writes <li> only — the <ol> itself stays the static one",
    !/<ol/.test(en.list.innerHTML) && /^<li>/.test(en.list.innerHTML));
  check("each row carries the reason and the testing prompt",
    state.every((t) => en.list.innerHTML.includes(t.why.en))
    && state.every((t) => en.list.innerHTML.includes(t.test.en)));
  check("the EN render uses the EN testing label", en.list.innerHTML.includes("Try this: ")
    && !en.list.innerHTML.includes("Pruébalo: "));

  const es = runHf2(state, "es");
  check("the SAME stored state renders Spanish",
    JSON.stringify(es.names) === JSON.stringify(state.map((t) => t.es)));
  check("the ES render uses the ES testing label", es.list.innerHTML.includes("Pruébalo: ")
    && !es.list.innerHTML.includes("Try this: "));
  // Cross-language leakage, both directions, all three fields.
  check("no Spanish leaks into the EN render",
    state.every((t) => !en.list.innerHTML.includes(t.es))
    && state.every((t) => !en.list.innerHTML.includes(t.why.es)));
  check("no English leaks into the ES render",
    state.every((t) => !es.list.innerHTML.includes(t.en))
    && state.every((t) => !es.list.innerHTML.includes(t.why.en)));
  // Positional correspondence: EN[i] and ES[i] are two halves of ONE pair —
  // the assertion that catches any per-language re-sort or name-keyed tiebreak.
  check("EN and ES renders correspond position by position",
    en.names.every((n, i) => state[i].en === n && es.names[i] === state[i].es));
}
{
  // The poison proof: the render must come from the STORE, not from answers.
  // Fixture E is a different POPULATED order — a renderer that recomputes from
  // answers produces E's sequence, visibly, where {} would look like "empty".
  const state = runProfile(FIXTURES.C, "en").analytics.trialFocus;
  const eNames = runProfile(FIXTURES.E, "en").analytics.trialFocus.map((t) => t.en);
  const got = runHf2(state, "en").names;
  check("rendering C's stored state can never produce E's order (no recompute path)",
    JSON.stringify(got) !== JSON.stringify(eNames)
    && JSON.stringify(got) === JSON.stringify(state.map((t) => t.en)));
  check("renderHf2Priorities never reads answers — statically true",
    !/\banswers\b/.test(HF2_FN));
  check("...and never calls the profile renderer", !/showProfileScreen/.test(HF2_FN));
}
{
  // Bounds and emptiness: 2-priority and 1-priority states render at length.
  const b = runProfile(FIXTURES.B, "en").analytics.trialFocus;
  check("a 2-priority state renders exactly 2 rows", runHf2(b, "en").names.length === 2);
  const h = runProfile(FIXTURES.H, "en").analytics.trialFocus;
  check("a 1-priority state renders exactly 1 row", runHf2(h, "en").names.length === 1);

  // Missing/invalid state hides the WHOLE section and empties the list.
  for (const [label, bad] of [
    ["an empty array", []],
    ["a wiped (undefined) field", undefined],
    ["a pre-widening shape (names only, no prose)", [{ en: "X", es: "Y" }]],
    ["entries missing the test prompt", [{ en: "X", es: "Y", why: { en: "w", es: "w2" } }]],
  ]) {
    const r = runHf2(bad, "en");
    check(`${label} hides the section entirely`,
      r.section.style.display === "none" && r.list.innerHTML === "");
  }
  // The hide is not the vacuous starting state: show first, then clear.
  const state = runProfile(FIXTURES.C, "en").analytics.trialFocus;
  const { els, doc } = makeDoc();
  const analytics = { trialFocus: state };
  const out = {};
  new Function("document", "analytics", "out", "langBox",
    `"use strict";
    var currentLang = 'en';
    ${ESCAPE_FN}
    ${L_FN}
    ${HF2_FN}
    out.run = function() { renderHf2Priorities(); };
    `)(doc, analytics, out, {});
  out.run();
  check("precondition: rendered visible with 3 rows first",
    els.get("hf2PrioritiesSection").style.display === ""
    && (els.get("hf2Priorities").innerHTML.match(/<li>/g) || []).length === 3);
  analytics.trialFocus = [];
  out.run();
  check("REGRESSION: clearing the state hides the section and empties the list",
    els.get("hf2PrioritiesSection").style.display === "none"
    && els.get("hf2Priorities").innerHTML === "");
}
{
  // Hostile copy cannot become markup: the renderer escapes every field.
  const hostile = [{ en: "<img src=x onerror=a>", es: "<b>x</b>",
    why: { en: "<script>alert(1)</script>", es: "w" },
    test: { en: "\" onmouseover=\"x", es: "t" } }];
  const r = runHf2(hostile, "en");
  check("hostile stored strings are escaped in the hf2 render",
    !r.list.innerHTML.includes("<script>") && !r.list.innerHTML.includes("<img")
    && r.list.innerHTML.includes("&lt;script&gt;"));
}

// ===========================================================================
// 5. THE PAYLOAD PROJECTION
// ===========================================================================
section("payload: bounded, allowlisted, pre-localized, ordered");
{
  const state = runProfile(FIXTURES.C, "en").analytics.trialFocus;
  for (const lang of ["en", "es"]) {
    const p = runProjection(state, lang);
    check(`[${lang}] three entries for a three-priority state`, p.length === 3);
    p.forEach((e, i) => {
      check(`[${lang}] entry ${i}: key set is exactly name/reason/test`,
        JSON.stringify(Object.keys(e).sort()) === JSON.stringify(["name", "reason", "test"]));
      check(`[${lang}] entry ${i}: every value is a non-empty string`,
        [e.name, e.reason, e.test].every((v) => typeof v === "string" && v.length > 0));
    });
    check(`[${lang}] order matches the stored order`,
      JSON.stringify(p.map((e) => e.name))
      === JSON.stringify(state.map((t) => t[lang])));
    check(`[${lang}] prose is pre-localized to ${lang}`,
      p.every((e, i) => e.reason === state[i].why[lang] && e.test === state[i].test[lang]));
  }
  // Nothing internal survives the projection.
  const blob = JSON.stringify(runProjection(state, "en"));
  check("no internal marker in the payload field",
    !/"(score|kind|rank|id|en|es|why)":/.test(blob));
  // Raw answer ids never appear in customer copy, so any hit is a leak.
  for (const raw of ["hip_pain", "yes_often", "back_pain", "cal_king", "sagging"]) {
    check(`no raw answer id "${raw}" in the payload field`, !blob.includes(raw));
  }
  check("the projection returns fresh objects, not references into the store",
    runProjection(state, "en")[0] !== state[0]);
}
{
  const b = runProfile(FIXTURES.B, "en").analytics.trialFocus;
  check("a 2-priority state ships 2 entries — never padded",
    runProjection(b, "en").length === 2);
  const h = runProfile(FIXTURES.H, "en").analytics.trialFocus;
  check("a 1-priority state ships 1 entry", runProjection(h, "en").length === 1);
  // Oversized state (can only arise from a defect) is capped at three.
  const ten = Array.from({ length: 10 }, (_, i) => ({
    en: "N" + i, es: "S" + i, why: { en: "w", es: "ws" }, test: { en: "t", es: "ts" } }));
  check("a corrupt oversized state is capped at 3", runProjection(ten, "en").length === 3);
  check("a wiped state ships an empty array", runProjection(undefined, "en").length === 0);
}

// ===========================================================================
// 6. STATIC WIRING
// ===========================================================================
section("static wiring: markup, placement, wipe inventory, isolation");
check("the section markup exists with a BARE <ol> (no class), statically empty",
  /<ol id="hf2Priorities"><\/ol>/.test(html));
check("the section ships hidden and carries the existing pattern's classes only",
  /<section class="hf2-review-section" id="hf2PrioritiesSection" style="display:none">/.test(html));
check("placement: after 'What we set out to solve', above the finalists",
  html.indexOf('id="hf2NeedsLabel"') < html.indexOf('id="hf2PrioritiesSection"')
  && html.indexOf('id="hf2PrioritiesSection"') < html.indexOf('id="hf2FinalistsLabel"'));
check("no new component class: the section introduces no class outside the existing pattern",
  (() => {
    const m = html.match(/<section class="hf2-review-section" id="hf2PrioritiesSection"[\s\S]*?<\/section>/);
    if (!m) return false;
    const classes = [...m[0].matchAll(/class="([^"]+)"/g)].flatMap((c) => c[1].split(/\s+/));
    return classes.every((c) => ["hf2-review-section", "hf2-review-section__label"].includes(c));
  })());
check("the label is written by renderHf2's copy map, bilingually",
  /hf2PrioritiesLabel: es \? 'Lo que probaremos juntos' : 'What we will test together',/.test(html));
check("renderHf2 renders priorities between the brief and the picks",
  /renderHf2Brief\(\);\s*renderHf2Priorities\(\);\s*renderHf2Picks\(\);/.test(html));
check("the list is in the wipe's content inventory",
  /'hf2SleepSystemSection', 'hf2Priorities',/.test(html));
check("the section returns to hidden through SESSION_LAYERS",
  /\{ id: 'hf2PrioritiesSection', display: 'none' \},/.test(html));
check("the payload literal keeps the shape session_async pins ('};' at six spaces)",
  /const payload = \{[\s\S]*?\n      \};/.test(html));
check("the compute block never references financing",
  !/financing/i.test(PROFILE_FN));
check("the widened mapping stores no score, kind or rank",
  !/score|kind|rank/.test((PROFILE_FN.match(/analytics\.trialFocus = topPriorities\.map[\s\S]*?\}\);/) || [""])[0]));
check("renderResultsTrialFocus is byte-identical to the 572d405 pin",
  TRIAL_FN === readFileSync(join(root, "tests", "fixtures", "sleep_brief_baseline_572d405.json"), "utf8")
    ? false // (guard against accidentally comparing to the wrong artifact)
    : /var focus = Array\.isArray\(analytics\.trialFocus\)\s*\? analytics\.trialFocus\.map\(function\(item\) \{ return L\(item\); \}\)\.filter\(Boolean\)/.test(TRIAL_FN));

// ===========================================================================
console.log(`\nConsultation priorities check: ${passed} passed, ${failed} failed`);
process.exit(failed === 0 ? 0 : 1);
