// Phase 1 exit gate — the recommendation-output regression fixture.
//
// docs/rebuild-roadmap.md, "Standing Phase 1 constraints": capture a fixture
// of fixed answer sets -> (top pick, tier assignment, ordered result list,
// computed firmness) at the Phase 1 baseline commit, and assert it unchanged
// by every Phase 1 PR alongside tests/scoring_isolation_check.mjs. This suite
// is that gate, built per the owner directive of 2026-08-12 (the open-decisions
// register entry "Phase 1 scoring-fixture exit gate" was Blake's to approve,
// and he did). It makes Invariant 2 — "nothing in Phase 1 changes what the
// engine computes" — executable rather than aspirational.
//
// WHAT IS PINNED, per scenario, from the REAL extracted engine (nothing here
// reimplements a calculation; every value is produced by executing source
// extracted verbatim from index.html):
//   - calculateScores(): the full per-mattress score map (asserted identical
//     EN vs ES, pinned once) and the per-mattress matchReasons per language;
//   - the resolved firmness input (the engine's own resolution line, executed:
//     answers.firmness if present, else the quiz slider default) and the
//     profile screen's computed feel classification (Plush/Medium/Firm word);
//   - window.showResults() derivation: per-tier ordered results with id,
//     score, pct and meetsMatchThreshold — which pins tier membership,
//     within-tier ordering, the >=60%-of-tier-max qualification, the cap of 3
//     and the back-fill to two — plus analytics.topPick and allMatches;
//   - the accessory engine: scoreAccessoriesFromAnswers() full ordered list
//     (id, score, matched, per-language reasons) and getSleepSystemViewModel()
//     step groups (support / adjustability / pillow / protection, each through
//     the same qualification, the support sub-type re-sort) plus
//     analytics.recommendedAccessories;
//   - showProfileScreen() engine state: analytics.trialFocus (the ordered 1-3
//     Sleep Brief priorities, bilingual), profileName (the 16-type profile
//     assignment), profileSubtitleByLang and profileBriefByLang.
//
// WHAT IS DELIBERATELY NOT PINNED: presentation. Sleep Brief HTML, card
// markup, chrome strings and layout are Phase 1's to change; this suite must
// never fire on an approved visual change. Only computed recommendation state
// is held. (The Sleep Brief's rendered bytes are separately pinned against
// the 572d405 baseline by tests/consultation_priorities_check.mjs for its own
// fixtures; that pin, not this one, is the one a future approved Sleep Brief
// change regenerates.)
//
// KNOWN ENGINE DEFECTS ARE BASELINE, NOT BUGS TO FIX HERE. The scoring
// case-fold defect and the unmatched quiz-tag vocabulary (roadmap 3.1 / 3.2)
// are captured exactly as they behave today. "Correcting" them would change
// what is recommended and is a Phase 3 decision requiring Blake. If a Phase 3
// change is ever approved, THIS fixture regenerates from the pre-change
// commit of that phase with its hash moved in the same reviewed diff.
//
// THE REGENERATION RATCHET (same doctrine as the consultation-priorities
// baseline): the fixture's sha256 is pinned below, so regenerating it
// requires editing two files, one of which is this comment telling the editor
// that a regenerated pin certifies whatever the change produced. The baseline
// was generated by executing the engine at commit 85c5c10 — the Phase 1
// baseline main (PR #37's merge). Do NOT regenerate from a tree whose engine
// has changed; that is the vacuity this suite exists to prevent.
//   node tests/phase1_output_regression_check.mjs                  -> compare + mutation proof
//   node tests/phase1_output_regression_check.mjs --write-baseline -> regenerate (ratchet applies)
//
// The mutation proof runs on every invocation: each entry in MUTATIONS edits
// the extracted engine source in memory (never on disk), re-runs the full
// snapshot, and REQUIRES at least one detected divergence from the baseline.
// A mutation that no longer applies (stale find-string) or that produces zero
// divergence fails the suite — the pin must stay demonstrably load-bearing
// for ordering, tier membership, thresholds, cap, back-fill, firmness,
// feature cap, top pick, priorities and accessories.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const html = readFileSync(join(root, "index.html"), "utf8");
const MATTRESSES = JSON.parse(readFileSync(join(root, "data", "mattresses.json"), "utf8"));
const QUIZ = JSON.parse(readFileSync(join(root, "data", "quiz.json"), "utf8"));
const ACCESSORIES = JSON.parse(readFileSync(join(root, "data", "accessories.json"), "utf8"));

// Baseline regenerated for the owner-approved Daybreak PR 1 scoring change
// (2026-08-13): the locally-made +25 bonus and its availability match reason
// were removed from calculateScores(). Generated from the engine as changed on
// top of 31a7e79; supersedes phase1_output_baseline_85c5c10.json.
const BASELINE_PATH = join(root, "tests", "fixtures", "phase1_output_baseline_daybreak_pr1.json");
// 2026-08-23 amendment (owner-authorized Sleep Brief copy change, Slice 5
// C10): the "Comfortable elevation" testing prose changed from "Try the
// finalist flat, ..." to "Try the mattress flat, ..." (ES "el finalista" ->
// "el colchón", provisional). The fixture's TWO prose strings — and ONLY those
// — moved (s3_family_combo_cold_plush_reflux_plus.profile.trialFocus[0].test
// .en/.es). Evidence: the established tool (--write-baseline) was run on the
// post-change tree and its output equals this fixture minus the obsolete
// feelWord field, which stays in the pinned bytes per the 2026-08-15
// amendment; no score, rank, pct, threshold or resolved-firmness byte moved.
// Hash moved in the same reviewed diff.
// 2026-08-29 amendment (owner-authorized item 1.3 first dark reason tranche):
// four per-feature catalog reasons were authored as DARK data (s5.reason_firm,
// s1.reason_support, b2.reason_firm, b7.reason_medium; EN at the top level of
// incoming/lacks_mattresses.json, ES under each model's es object). The
// engine reads m.reasons in BOTH language passes and nothing reads
// reasons_es, so the ONLY pinned output that moved is the per-language
// matchReasons harvest: exactly 52 cells —
// scenarios.*.matchReasons.{en,es}.{s1,s5,b2,b7} in the nine reached
// scenarios (s1.support 8/10, b7.medium 8/10, s5.firm 5/10, b2.firm 5/10;
// s9_empty_defaults untouched), each gaining one appended element. The ES
// cells hold the ENGLISH text: the engine has no Spanish reason reader, and no
// customer sees either language (the reason surfaces stay omitted under
// PR #63). No score, rank, pct, tier, threshold, cap, back-fill,
// resolved-firmness, accessory, profile or rendered byte moved, and no engine
// source changed. Evidence: the established tool (--write-baseline) was run on
// the pre-change and post-change trees in temp copies; the post-change output
// equals this fixture minus the obsolete feelWord field (retained per the
// 2026-08-15 amendment); a structural path diff of the two outputs lists
// exactly the 52 cells above and nothing else; reverting only those 52 cells
// reproduces the previous fixture bytes (sha e7e5c27d…). Hash moved in the
// same reviewed diff. The catalog-data mutations M1–M4 and the tranche
// non-triviality pins in section 5 make this bounded amendment load-bearing.
// 2026-08-29 amendment, tranche 2 (owner-authorized item 1.3 second dark reason
// tranche; Decision B approved separately from the eight Decision A strings):
// eight further per-feature catalog reasons were authored as DARK data —
// s4/s2/s8/b4/b6.reason_firm, s6.reason_medium, s7/b5.reason_plush (EN top
// level, ES under each model's es object). Same mechanism as tranche 1: the
// engine reads m.reasons in BOTH language passes and nothing reads
// reasons_es, so the ONLY pinned output that moved is the per-language
// matchReasons harvest — exactly 86 cells, scenarios.*.matchReasons.{en,es}.
// {s4,s2,s8,s6,s7,b4,b6,b5} in the nine reached scenarios (s6.medium 8/10;
// s4, s2, s8, b4, b6.firm 5/10 each; s7, b5.plush 5/10 each;
// s9_empty_defaults untouched), each gaining one appended element; the
// tranche-1 cells (52) are byte-identical; cumulative 138 (69 EN + 69 ES).
// The ES cells hold the ENGLISH text (recorded, not approved). No score,
// rank, pct, tier, threshold, cap, back-fill, resolved-firmness, accessory,
// profile or rendered byte moved; no engine source changed. Evidence: the
// established tool (--write-baseline) run on the pre- and post-change trees in
// temp copies; post-change output == this fixture minus the obsolete feelWord
// field (retained); the structural path diff lists exactly the 86 cells and
// nothing else; reverting only those 86 cells reproduces the tranche-1 fixture
// bytes (sha 24dad016…). Hash moved in the same reviewed diff; the per-slot
// removal mutations, M5/M6 probes and the 12-pair non-triviality pins below
// make this bounded amendment load-bearing.
// 2026-08-30 amendment (owner-authorized item 3.7 step-4 change P3, second of
// P2 -> P3 -> P1): within the PILLOW group, readSleepSystemGroups() now ranks
// a pillow that at least one answer fired for (`matched`) above a pillow
// carried by its catalog default score alone - a stable sort applied after
// qualification, so the cap / back-fill and the threshold stamp are
// untouched. On the shipped catalog this reorders the two pillows for
// exactly the non-hot BACK sleepers (the Flow carries position_back 1; the
// gel pillow only default 2): fixture scenarios s1 and s5. The ONLY pinned
// cells that moved are 56 - scenarios.{s1,s5}.accessories.{en,es}.groups
// .pillow[0..1] and .recommendedAccessories[0..1] (ids, scores, stamps and
// the projection swap places; no value is new). Every other cell - the
// full scorer order (`ordered`), every score, rank, pct, tier, threshold,
// cap, back-fill, resolved firmness, profile and matchReason - is
// byte-identical. Evidence: the established tool (--write-baseline) run on
// the pre- and post-change trees in temp copies; the structural path diff
// lists exactly those 56 cells and nothing else; the patched fixture equals
// the post-change output minus the retained obsolete feelWord field;
// reverting only those 56 cells reproduces the previous fixture bytes (sha
// d973fae2...). Hash moved in the same reviewed diff; the "P3 matched-first
// pillow rank removed" mutation below makes the amendment load-bearing.
const BASELINE_SHA256 = "35c1c70e9e37befa67782e54a937cbfe932cea672862c65bf30d4660732f1dce";

const WRITE_MODE = process.argv.includes("--write-baseline");

let passed = 0, failed = 0;
function check(label, cond, detail) {
  if (cond) { passed++; console.log(`  [ok] ${label}`); }
  else { failed++; console.log(`  [FAIL] ${label}${detail ? " — " + detail : ""}`); }
  return cond;
}
function section(name) { console.log(`\n-- ${name} --`); }
function grab(re, what) {
  const m = html.match(re);
  check(`extracted ${what}`, !!m);
  return m ? m[0] : "";
}

// ---------- extractions ------------------------------------------------------
section("extraction");
const CALC_FN = grab(/function calculateScores\(\)\s*\{[\s\S]*?\r?\n    \}/, "calculateScores()");
const QUALIFY_FN = grab(/function qualifyRankedChoices\([\s\S]*?\r?\n    \}/, "qualifyRankedChoices()");
const SHOW_RESULTS_FN = grab(/window\.showResults = function\(\) \{[\s\S]*?\r?\n    \}/, "window.showResults");
const SCORE_ACC_FN = grab(/function scoreAccessoriesFromAnswers\(\)\s*\{[\s\S]*?\r?\n    \}/, "scoreAccessoriesFromAnswers()");
const CAT_FN = grab(/function sleepSystemCategory\([\s\S]*?\r?\n    \}/, "sleepSystemCategory()");
const STEP_FN = grab(/function sleepSystemStepForItem\([\s\S]*?\r?\n    \}/, "sleepSystemStepForItem()");
const VIEWMODEL_FN = grab(/function getSleepSystemViewModel\(\)\s*\{[\s\S]*?\r?\n    \}/, "getSleepSystemViewModel()");
// Slice 5 C3: the engine grouping now lives in readSleepSystemGroups(), which
// the view model composes over. Extracted BESIDE the view model so the
// fixture-facing entry keeps its name; the groups it yields must remain
// byte-identical (the fixture pins them per step).
const READGROUPS_FN = grab(/function readSleepSystemGroups\(\)\s*\{[\s\S]*?\r?\n    \}/, "readSleepSystemGroups()");
const FINALIST_FN = grab(/function getSleepSystemFinalist\(\)\s*\{[\s\S]*?\r?\n    \}/, "getSleepSystemFinalist()");
// Slice 5 C2: getSleepSystemFinalist() now delegates to the D5b resolver. The
// resolver is extracted BESIDE it (not instead of it) so the fixture-facing
// entry keeps its name and shape; the fixture stays null (nothing is seeded).
const RESOLVER_FN = grab(/function resolveFinalistState\(\)\s*\{[\s\S]*?\r?\n    \}/, "resolveFinalistState()");
const PROFILE_FN = grab(/function showProfileScreen\(\) \{[\s\S]*?\r?\n    \}\r?\n/, "showProfileScreen()");
const L_FN = grab(/function L\(obj\) \{[\s\S]*?\r?\n    \}/, "L()");
const ESCAPE_FN = grab(/function escapeHtml\([\s\S]*?\r?\n    \}/, "escapeHtml()");
// Slice 2 collaborators the render calls. The constellation is executed for
// real (it is answer-derived, so a broken one would surface here too);
// reduced motion is stubbed off because the entry animation is presentation,
// and this suite pins engine state only.
const SIGNATURE_FN = grab(/function buildSleepSignatureSvg\(answers\) \{[\s\S]*?\r?\n    \}/, "buildSleepSignatureSvg()");
if (failed) { console.log("\nextraction failed — aborting"); process.exit(1); }

// The engine's own firmness-resolution line, executed as-is. This is the
// "computed firmness" pin: the value every scoring pass runs against.
const FIRM_LINE = (CALC_FN.match(/const firmnessVal = [^\n]+;/) || [""])[0];
check("extracted the firmness resolution line", !!FIRM_LINE);

// ---------- scenarios --------------------------------------------------------
// Every id below exists in data/quiz.json. Solo scenarios omit
// partner_disturbance (the quiz skips it via skipIf). There is deliberately no
// `budget` answer: no budget question exists in the shipped quiz, so the
// accessory scorer's budget branch is unreachable in a real session and is
// left unexercised rather than pinned through an impossible input.
const SCENARIOS = {
  s1_solo_back_firm_no_issues: {
    sleep_quality: "well", trigger: "upgrade", mattress_size: "king",
    partner_sleep: "solo", sleep_position: "back", body_type: "athletic",
    temperature: "comfortable", firmness: 8, current_mattress_age: "under_2",
    sleep_issues: ["none"], health_conditions: ["none"]
  },
  s2_partner_side_hot_backpain_snoring: {
    sleep_quality: "poor", trigger: "pain", mattress_size: "queen",
    partner_sleep: "partner", partner_disturbance: "yes_often",
    sleep_position: "side", body_type: "average", temperature: "hot",
    firmness: 4, current_mattress_age: "eight_fifteen",
    sleep_issues: ["back_pain", "hot"], health_conditions: ["snoring"]
  },
  s3_family_combo_cold_plush_reflux_plus: {
    sleep_quality: "fair", trigger: "worn_out", mattress_size: "full",
    partner_sleep: "family", partner_disturbance: "sometimes",
    sleep_position: "combo", body_type: "plus", temperature: "cold",
    firmness: 2, current_mattress_age: "fifteen_plus",
    sleep_issues: ["hip_pain", "sagging"], health_conditions: ["reflux"]
  },
  s4_partner_stomach_cold_firm_sagging: {
    sleep_quality: "okay", trigger: "moving", mattress_size: "king",
    partner_sleep: "partner", partner_disturbance: "yes_often",
    sleep_position: "stomach", body_type: "average", temperature: "cold",
    firmness: 8, current_mattress_age: "three_seven",
    sleep_issues: ["sagging"], health_conditions: []
  },
  s5_motion_dominant_tossing: {
    sleep_quality: "fair", trigger: "browsing", mattress_size: "queen",
    partner_sleep: "partner", partner_disturbance: "yes_often",
    sleep_position: "back", body_type: "average", temperature: "comfortable",
    firmness: 5, current_mattress_age: "not_sure",
    sleep_issues: ["tossing"], health_conditions: ["none"]
  },
  s6_solo_side_pressure_relief: {
    sleep_quality: "poor", trigger: "pain", mattress_size: "twin_xl",
    partner_sleep: "solo", sleep_position: "side", body_type: "petite",
    temperature: "comfortable", firmness: 3, current_mattress_age: "eight_fifteen",
    sleep_issues: ["hip_pain", "stiff"], health_conditions: ["nerve_pain", "extra_support"]
  },
  s7_partner_combo_opposite_allergies: {
    sleep_quality: "okay", trigger: "upgrade", mattress_size: "cal_king",
    partner_sleep: "partner", partner_disturbance: "rarely",
    sleep_position: "combo", body_type: "different", temperature: "opposite",
    firmness: 6, current_mattress_age: "three_seven",
    sleep_issues: ["too_soft"], health_conditions: ["allergies"]
  },
  s8_no_idea_hot_aging: {
    sleep_quality: "fair", trigger: "worn_out", mattress_size: "full",
    partner_sleep: "solo", sleep_position: "no_idea", body_type: "average",
    temperature: "hot", firmness: 5, current_mattress_age: "fifteen_plus",
    sleep_issues: ["hot", "tossing"], health_conditions: ["getting_older"]
  },
  // Falls through the entire profile chain to the firmness branches: no pain,
  // no temperature extreme, no partner, medium firmness -> The Goldilocks.
  // Exists so the isPlush/isMedium boundaries are load-bearing for the
  // 16-type profile assignment (the plush-boundary mutation flips this one).
  s10_solo_goldilocks_medium: {
    sleep_quality: "okay", trigger: "browsing", mattress_size: "queen",
    partner_sleep: "solo", sleep_position: "side", body_type: "average",
    temperature: "comfortable", firmness: 4, current_mattress_age: "three_seven",
    sleep_issues: ["none"], health_conditions: ["none"]
  },
  // Bounds: an empty answer set exercises every default the engine owns —
  // the slider default, the '' position, the solo share phrase, the minimum
  // priority count. Same doctrine as fixture H in the consultation suite.
  s9_empty_defaults: {}
};

// ---------- harness ----------------------------------------------------------
function domShim() {
  const els = new Map();
  const make = (id) => {
    const classes = new Set();
    return {
      id, innerHTML: "", textContent: "", style: {},
      classList: {
        add: (c) => classes.add(c), remove: (c) => classes.delete(c),
        contains: (c) => classes.has(c)
      },
      setAttribute() {}, getAttribute: () => null, focus() {}
    };
  };
  return {
    els,
    doc: {
      getElementById: (id) => { if (!els.has(id)) els.set(id, make(id)); return els.get(id); },
      querySelector: () => null, querySelectorAll: () => []
    }
  };
}

// A window shim that FAILS LOUDLY on an undeclared read.
//
// Every harness below used to hand the engine `var window = {}`. A plain
// object answers EVERY property read with `undefined` and says nothing, so an
// engine that started consulting session state through the global — the
// Payment Choice model's `window._payPref` / `window._payExplored` being the
// live example, but equally `window._savedPicks` or any future customer
// value — would keep computing, keep producing a snapshot that matched the
// pinned baseline, and this suite would certify the isolation it can no
// longer see. `typeof window._payPref === 'undefined'` is the same escape
// wearing a guard: on a plain object it is simply true, forever.
//
// The Proxy inverts the default. Reads of a string key that was never written
// by the engine itself and is not in this harness's DECLARED seed throw, so
// reaching for state the harness does not supply is a loud failure instead of
// a silent `undefined`. Writes are allowed and are readable afterwards
// (`window.showResults = fn; window.showResults()` is the real call shape).
// Symbol reads return undefined: `JSON.stringify`, `console.log` and the
// spread operator probe Symbol.toPrimitive / Symbol.iterator on anything they
// touch, and turning those probes into failures would only make the harness
// fragile without protecting anything.
//
// The seeds are the audited set of window properties the extracted engine
// functions actually read on this baseline:
//   showResults()            -> none (it only ASSIGNS window.showResults)
//   getSleepSystemFinalist() -> _savedPicks, _favoriteMattressId
//   showProfileScreen()      -> _sleepSignatureEntry
// Adding a seed is a reviewed act: it declares that the engine legitimately
// reads that global, which is exactly the claim this suite exists to police.
function throwingWindow(seed = {}) {
  const store = Object.assign(Object.create(null), seed);
  return new Proxy(store, {
    get(t, k) {
      if (typeof k === "symbol") return undefined;
      if (k in t) return t[k];
      throw new Error(
        `engine read window.${String(k)}, which this harness never declared — ` +
        `the recommendation engine must not consult session/global state`);
    },
    set(t, k, v) { t[k] = v; return true; },
    has(t, k) { return typeof k === "symbol" ? false : k in t; },
    deleteProperty(t, k) { delete t[k]; return true; }
  });
}

const clone = (x) => JSON.parse(JSON.stringify(x));

// Executes the engine's own firmness-resolution line.
function runFirmness(answers) {
  return new Function("answers", "QUESTIONS", `"use strict";
    const firmnessQ = QUESTIONS.find(q => q.id === 'firmness');
    ${FIRM_LINE}
    return firmnessVal;`)(clone(answers), QUIZ.questions);
}

// Executes the real calculateScores().
// `mattresses` (2026-08-29): the catalog-data mutations in section 5 substitute
// an in-memory catalog copy; the engine source is untouched by them.
function runScores(answers, lang, calcSrc = CALC_FN, mattresses = MATTRESSES) {
  return new Function("MATTRESSES", "QUESTIONS", "answers", "currentLang", `"use strict";
    ${calcSrc}
    return calculateScores();`)(mattresses, QUIZ.questions, clone(answers), lang);
}

// Executes the real window.showResults() whole — the tier derivation, the
// qualification/cap/back-fill, pct, topPick and allMatches — against shims for
// its render/analytics side effects.
function runResults(answers, lang, { calcSrc = CALC_FN, qualifySrc = QUALIFY_FN, showSrc = SHOW_RESULTS_FN, mattresses = MATTRESSES } = {}) {
  const { doc } = domShim();
  const out = {};
  new Function("document", "window", "MATTRESSES", "QUESTIONS", "answers", "currentLang", "out", `"use strict";
    var analytics = { log: function(){} };
    var _resultsState = null;
    function _renderResults() {}
    function showScreen() {}
    function sessionSafeSummary() { return {}; }
    ${calcSrc}
    ${qualifySrc}
    ${showSrc};
    window.showResults();
    out.state = _resultsState;
    out.analytics = analytics;`)(doc, throwingWindow(), mattresses, QUIZ.questions, clone(answers), lang, out);
  const slim = {};
  for (const tier of ["gold", "silver", "bronze"]) {
    slim[tier] = out.state.tierData[tier].map((m) => ({
      id: m.id, score: m.score, pct: m.pct, meetsMatchThreshold: m.meetsMatchThreshold
    }));
  }
  return { tierData: slim, topPick: out.analytics.topPick, allMatches: out.analytics.allMatches };
}

// Executes the real accessory engine: the answer-driven scorer and the Sleep
// System view-model grouping (qualification + support sub-type re-sort).
function runAccessories(answers, lang, { accSrc = SCORE_ACC_FN, qualifySrc = QUALIFY_FN, vmSrc = VIEWMODEL_FN, groupsSrc = READGROUPS_FN, stepSrc = STEP_FN } = {}) {
  const out = {};
  new Function("ACCESSORIES", "window", "answers", "currentLang", "out", `"use strict";
    var _resultsState = null;
    var analytics = {};
    ${qualifySrc}
    ${CAT_FN}
    ${stepSrc}
    ${accSrc}
    ${RESOLVER_FN}
    ${FINALIST_FN}
    ${groupsSrc}
    ${vmSrc}
    out.ordered = scoreAccessoriesFromAnswers();
    out.vm = getSleepSystemViewModel();
    out.analytics = analytics;`)(ACCESSORIES,
      throwingWindow({ _savedPicks: [], _favoriteMattressId: "" }),
      clone(answers), lang, out);
  const slimGroups = {};
  for (const step of ["support", "adjustability", "pillow", "protection"]) {
    slimGroups[step] = out.vm.groups[step].map((a) => ({
      id: a.id, score: a.score, meetsMatchThreshold: a.meetsMatchThreshold
    }));
  }
  return {
    ordered: out.ordered.map((a) => ({ id: a.id, score: a.score, matched: a.matched, reasons: a.reasons })),
    groups: slimGroups,
    recommendedAccessories: out.analytics.recommendedAccessories,
    finalist: out.vm.finalist
  };
}

// Executes the real showProfileScreen() — same stub set the consultation
// suite proves sufficient — and returns only engine-computed state.
function runProfile(answers, lang, profileSrc = PROFILE_FN) {
  const { els, doc } = domShim();
  const analytics = { trialFocus: [], log() {} };
  new Function("document", "window", "answers", "currentLang", "analytics", `"use strict";
    function t(k) { return k; }
    function showScreen() {}
    function dfmReducedMotion() { return false; }
    var _briefOpenPriority = null;
    ${ESCAPE_FN}
    ${L_FN}
    ${SIGNATURE_FN}
    ${profileSrc}
    showProfileScreen();`)(doc, throwingWindow({ _sleepSignatureEntry: false }),
      clone(answers), lang, analytics);
  return {
    trialFocus: analytics.trialFocus,
    profileName: analytics.profileName,
    profileSubtitleByLang: analytics.profileSubtitleByLang,
    profileBriefByLang: analytics.profileBriefByLang
  };
}

// ---------- harness self-proof ----------------------------------------------
// A guard nobody exercises is a guard nobody has. These run the throwing shim
// through the exact escapes it exists to close, so the shim cannot quietly
// degrade into the plain `{}` it replaced.
section("window shim fails loudly (harness non-vacuity)");
{
  const threw = (fn) => { try { fn(); return false; } catch { return true; } };
  const w = throwingWindow({ _savedPicks: [] });
  check("an undeclared window read throws", threw(() => w._payPref));
  check("a typeof guard on an undeclared window read throws too",
    threw(() => typeof w._payExplored));
  check("a declared seed reads normally without throwing",
    !threw(() => w._savedPicks) && Array.isArray(w._savedPicks));
  check("a value the engine writes is readable afterwards",
    !threw(() => { w.showResults = () => 7; return w.showResults(); })
    && w.showResults() === 7);
  check("symbol probes stay silent (stringify/spread must not become failures)",
    !threw(() => JSON.stringify({ w: String(typeof w) }))
    && !threw(() => w[Symbol.iterator]));
  check("`in` reports only what is declared or written",
    !("_payPref" in w) && "_savedPicks" in w);
  // The three real harness seeds, pinned: widening one is a reviewed act.
  check("the declared seed inventory is exactly the audited engine globals",
    JSON.stringify([
      Object.keys(Object.assign({}, throwingWindow())),
      Object.keys(Object.assign({}, throwingWindow({ _savedPicks: [], _favoriteMattressId: "" }))),
      Object.keys(Object.assign({}, throwingWindow({ _sleepSignatureEntry: false })))
    ]) === JSON.stringify([[], ["_savedPicks", "_favoriteMattressId"], ["_sleepSignatureEntry"]]));
}

// ---------- snapshot ---------------------------------------------------------
function buildSnapshot(overrides = {}) {
  const snap = { baselineCommit: "daybreak-pr1@31a7e79", scenarios: {} };
  for (const [name, answers] of Object.entries(SCENARIOS)) {
    const en = runScores(answers, "en", overrides.calcSrc, overrides.mattresses);
    const es = runScores(answers, "es", overrides.calcSrc, overrides.mattresses);
    if (JSON.stringify(en.scores) !== JSON.stringify(es.scores)) {
      snap.scenarios[name] = { LANGUAGE_DIVERGENCE_IN_SCORES: true };
      continue;
    }
    const profileEn = runProfile(answers, "en", overrides.profileSrc);
    const profileEs = runProfile(answers, "es", overrides.profileSrc);
    snap.scenarios[name] = {
      answers,
      firmnessResolved: runFirmness(answers),
      scores: en.scores,
      matchReasons: { en: en.matchReasons, es: es.matchReasons },
      results: runResults(answers, "en", overrides),
      accessories: {
        en: runAccessories(answers, "en", overrides),
        es: runAccessories(answers, "es", overrides)
      },
      profile: {
        trialFocus: profileEn.trialFocus,
        profileName: profileEn.profileName,
        profileSubtitleByLang: profileEn.profileSubtitleByLang,
        profileBriefByLang: profileEn.profileBriefByLang,
        trialFocusLangStable:
          JSON.stringify(profileEn.trialFocus) === JSON.stringify(profileEs.trialFocus)
      }
    };
  }
  return snap;
}

// Deep structural diff with path reporting — the failure names exactly which
// scenario, surface and field moved.
function diffPaths(a, b, path = "", out = []) {
  if (out.length >= 40) return out;
  if (a === b) return out;
  const ta = Object.prototype.toString.call(a), tb = Object.prototype.toString.call(b);
  if (ta !== tb) { out.push(`${path}: ${JSON.stringify(a)} != ${JSON.stringify(b)}`); return out; }
  if (Array.isArray(a)) {
    if (a.length !== b.length) out.push(`${path}.length: ${a.length} != ${b.length}`);
    const n = Math.min(a.length, b.length);
    for (let i = 0; i < n; i++) diffPaths(a[i], b[i], `${path}[${i}]`, out);
    return out;
  }
  if (a && typeof a === "object") {
    const keys = new Set([...Object.keys(a), ...Object.keys(b)]);
    for (const k of keys) diffPaths(a[k], b[k], path ? `${path}.${k}` : k, out);
    return out;
  }
  out.push(`${path}: ${JSON.stringify(a)} != ${JSON.stringify(b)}`);
  return out;
}

// ---------- write mode -------------------------------------------------------
if (WRITE_MODE) {
  const snap = buildSnapshot();
  writeFileSync(BASELINE_PATH, JSON.stringify(snap, null, 2) + "\n");
  const sha = createHash("sha256")
    .update(readFileSync(BASELINE_PATH).toString("utf8").split("\r\n").join("\n"))
    .digest("hex");
  console.log(`baseline written: ${BASELINE_PATH}`);
  console.log(`sha256 (LF-normalized): ${sha}`);
  console.log("RATCHET: update BASELINE_SHA256 in this suite in the SAME reviewed diff,");
  console.log("and only ever regenerate from the pre-change commit of an approved engine change.");
  process.exit(0);
}

// ---------- 1. the baseline fixture is the reviewed one ----------------------
section("baseline fixture integrity");
check("baseline fixture exists", existsSync(BASELINE_PATH));
const BASELINE_RAW = readFileSync(BASELINE_PATH).toString("utf8");
check("fixture matches its pinned sha256 (LF-normalized)",
  createHash("sha256").update(BASELINE_RAW.split("\r\n").join("\n")).digest("hex") === BASELINE_SHA256);
const BASELINE = JSON.parse(BASELINE_RAW);

// ---------- 2. the live engine reproduces the baseline exactly ---------------
section("engine outputs match the Phase 1 baseline (daybreak_pr1)");
const live = buildSnapshot();
// Slice 2 (owner amendment, 2026-08-15). `profile.feelWord` was harvested by
// scraping the Sleep Brief's meta strip — a presentation surface the approved
// D1 recomposition removed. The fixture and its sha are deliberately UNCHANGED
// (regenerating an oracle from the code under review is what the ratchet
// exists to prevent), so the field still sits in the pinned bytes; it is
// excluded from the comparison rather than re-derived from any rendered
// markup. Nothing is lost: the engine's resolved firmness is pinned directly
// as `firmnessResolved` below, and the customer-visible firmness wording is
// pinned verbatim by the Sleep Brief reflection oracle in
// tests/consultation_priorities_check.mjs.
const OBSOLETE_PROFILE_FIELDS = ["feelWord"];
function withoutObsoletePresentation(scenario) {
  if (!scenario || !scenario.profile) return scenario;
  const profile = { ...scenario.profile };
  for (const k of OBSOLETE_PROFILE_FIELDS) delete profile[k];
  return { ...scenario, profile };
}
// The exclusion must stay exactly this narrow: any OTHER pinned profile field
// that stops being produced is a regression, not a presentation retirement.
{
  const first = Object.keys(SCENARIOS)[0];
  const dropped = Object.keys(BASELINE.scenarios[first].profile)
    .filter((k) => !(k in live.scenarios[first].profile));
  check("the only pinned profile field excluded from comparison is the obsolete feelWord",
    JSON.stringify(dropped) === JSON.stringify(OBSOLETE_PROFILE_FIELDS), dropped.join(", "));
}
for (const name of Object.keys(SCENARIOS)) {
  const diffs = diffPaths(withoutObsoletePresentation(BASELINE.scenarios[name]),
    live.scenarios[name], name);
  check(`${name}: every pinned output identical`, diffs.length === 0,
    diffs.slice(0, 5).join(" | "));
}
check("scenario set matches the baseline's",
  JSON.stringify(Object.keys(BASELINE.scenarios)) === JSON.stringify(Object.keys(SCENARIOS)));

// ---------- 3. the fixture actually exercises what it claims to pin ----------
section("fixture non-triviality");
{
  const all = Object.values(BASELINE.scenarios);
  // On the shipped catalog the mattress tiers never trigger back-fill — every
  // tier's runner-up clears 60% of the tier max in all nine scenarios (scores
  // cluster because firmness pays everything). The floor lives in the SHARED
  // qualifyRankedChoices and demonstrably fires in the accessory groups, so
  // the property is pinned there and proven load-bearing by the back-fill
  // mutation below, which diverges through the accessory surface.
  check("back-fill fired somewhere (an entry below the 60% threshold was kept)",
    all.some((s) => ["gold", "silver", "bronze"].some(
      (t) => s.results.tierData[t].some((m) => m.meetsMatchThreshold === false)))
    || all.some((s) => ["support", "adjustability", "pillow", "protection"].some(
      (g) => s.accessories.en.groups[g].some((a) => a.meetsMatchThreshold === false))));
  check("the cap of 3 binds somewhere (no tier list exceeds 3, at least one hits 3)",
    all.every((s) => ["gold", "silver", "bronze"].every((t) => s.results.tierData[t].length <= 3))
    && all.some((s) => ["gold", "silver", "bronze"].some((t) => s.results.tierData[t].length === 3)));
  check("priority count varies across scenarios (engine produces 1-3, never padded)",
    new Set(all.map((s) => s.profile.trialFocus.length)).size >= 2
    && all.every((s) => s.profile.trialFocus.length >= 1 && s.profile.trialFocus.length <= 3));
  check("resolved firmness varies and includes the slider default",
    new Set(all.map((s) => s.firmnessResolved)).size >= 4
    && BASELINE.scenarios.s9_empty_defaults.firmnessResolved
       === QUIZ.questions.find((q) => q.id === "firmness").defaultValue);
  // Band coverage, expressed on the ENGINE's resolved firmness rather than on
  // any rendered wording: the scenario set must still exercise the plush,
  // medium and firm bands the engine distinguishes.
  check("the scenario set spans the plush, medium and firm firmness bands",
    all.some((s) => s.firmnessResolved <= 3)
    && all.some((s) => s.firmnessResolved >= 4 && s.firmnessResolved <= 6)
    && all.some((s) => s.firmnessResolved >= 7),
    all.map((s) => s.firmnessResolved).join(","));
  check("EN and ES accessory reasons genuinely differ (language reaches the engine)",
    all.some((s) => JSON.stringify(s.accessories.en.ordered) !== JSON.stringify(s.accessories.es.ordered)));
  check("trialFocus is language-stable (bilingual objects, not per-language recompute)",
    all.every((s) => s.profile.trialFocusLangStable === true));
  check("every scenario has a top pick and it is Gold #1",
    all.every((s) => s.results.topPick && s.results.topPick.tier === "gold"
      && s.results.topPick.name === MATTRESSES.gold.find(
           (m) => m.id === s.results.tierData.gold[0].id).name));
  // Slice 5 C0 — label corrected. This harness seeds EMPTY picks, a null
  // _resultsState and an empty analytics object, so every fallback branch of
  // getSleepSystemFinalist() (saved[0], tierData.gold[0], analytics.topPick)
  // is structurally unreachable from here. The assertion below therefore
  // proves only that the fixture's `finalist` field is null under an EMPTY
  // session — it does not and cannot prove the function never returns engine
  // output. The seeded characterization that follows is what sees the
  // fallbacks; the earlier label ("session state, not engine output") claimed
  // what this line cannot show.
  check("the fixture's finalist field is null under the EMPTY session this harness seeds",
    all.every((s) => s.accessories.en.finalist === null && s.accessories.es.finalist === null));

  // Seeded characterization (Slice 5 C0). Runs the REAL getSleepSystemFinalist()
  // with populated engine output and no explicit favorite, and records what it
  // returns TODAY. Written as characterization, not aspiration: at 4a76503 the
  // function falls through to saved[0] / tierData.gold[0] / analytics.topPick.
  // The resolver commit that lands the D5b semantics must flip these to the
  // honest outcome (null — no explicit finalist) WITHOUT moving the fixture,
  // which stays null because the fixture harness seeds nothing.
  {
    const probe = new Function("window", "_resultsState", "analytics",
      RESOLVER_FN + "\n" + FINALIST_FN + "\n return getSleepSystemFinalist();");
    const gold = [{ id: "gX", name: "GX" }];
    const top = { name: "TOP", tier: "gold" };
    const r1 = probe({ _savedPicks: [{ id: "g5" }, { id: "g6" }], _favoriteMattressId: "" }, null, {});
    const r2 = probe({ _savedPicks: [], _favoriteMattressId: "" }, { tierData: { gold } }, {});
    const r3 = probe({ _savedPicks: [], _favoriteMattressId: "" }, { tierData: { gold: [] } }, { topPick: top });
    const r4 = probe({ _savedPicks: [{ id: "g6" }], _favoriteMattressId: "g5" }, null, {});
    const promotes = r1 && r1.id === "g5" && r2 && r2.id === "gX" && r3 === top && r4 && r4.id === "g6";
    const honest = r1 === null && r2 === null && r3 === null && r4 === null;
    check("[characterization] getSleepSystemFinalist() with no explicit favorite is EITHER the shipped silent promotion (saved[0] / gold[0] / topPick / orphaned->saved[0]) OR the honest null — never a third thing",
      promotes || honest);
    console.log(`  [info] finalist fallback characterization at this head: ${promotes ? "SILENT PROMOTION (pre-D5b shipped behaviour)" : honest ? "HONEST NULL (D5b semantics landed)" : "UNRECOGNISED"}`);
  }
  // Catalog ratchet: today the support group is a single item, which is WHY
  // the sub-type re-sort carries no mutation (see the MUTATIONS comment).
  // When this fails, the catalog gained support sub-types — add the re-sort
  // mutation in the same change.
  check("support group is single-item on the shipped catalog (re-sort has nothing to reorder)",
    all.every((s) => s.accessories.en.groups.support.length === 1));
}

// ---------- 4. mutation proof: the pin is load-bearing ------------------------
// Each mutation edits extracted source IN MEMORY, rebuilds the snapshot and
// must diverge from the baseline. Zero divergence = vacuous pin = FAIL.
section("mutation proof (every protected output class is caught)");
const MUTATIONS = [
  { name: "tier ordering reversed", key: "showSrc", src: SHOW_RESULTS_FN,
    find: "scores[b.id] - scores[a.id]", replace: "scores[a.id] - scores[b.id]" },
  { name: "qualification threshold 0.6 -> 0.5 (tier membership)", key: "qualifySrc", src: QUALIFY_FN,
    find: "maxScore * 0.6", replace: "maxScore * 0.5" },
  { name: "result cap 3 -> 4", key: "qualifySrc", src: QUALIFY_FN,
    find: ".slice(0, 3)", replace: ".slice(0, 4)" },
  { name: "back-fill floor 2 -> 1", key: "qualifySrc", src: QUALIFY_FN,
    find: "Math.min(2, ranked.length)", replace: "Math.min(1, ranked.length)" },
  { name: "firmness ladder halved", key: "calcSrc", src: CALC_FN,
    find: "50 - diff * 10", replace: "50 - diff * 5" },
  { name: "firmness resolution ignores the answer", key: "calcSrc", src: CALC_FN,
    find: "answers['firmness'] !== undefined ? answers['firmness'] : firmnessQ.defaultValue",
    replace: "firmnessQ.defaultValue" },
  // The "locally-made bonus 25 -> 0" mutation retired with the bonus itself
  // (owner-approved removal, Daybreak PR 1, 2026-08-13): the block no longer
  // exists to mutate. Its absence is pinned by scoring_isolation_check.mjs
  // (the engine may not reference locallyMade at all) and by this suite's
  // baseline, which was regenerated from the bonus-free engine.
  { name: "feature cap 5 -> 3", key: "calcSrc", src: CALC_FN,
    find: "const FEATURE_CAP = 5;", replace: "const FEATURE_CAP = 3;" },
  { name: "top pick reads Silver instead of Gold", key: "showSrc", src: SHOW_RESULTS_FN,
    find: "var goldTop3 = tierData.gold;", replace: "var goldTop3 = tierData.silver;" },
  { name: "priorities ordering reversed", key: "profileSrc", src: PROFILE_FN,
    find: "priorities.sort(function(a, b) { return b.score - a.score; });",
    replace: "priorities.sort(function(a, b) { return a.score - b.score; });" },
  { name: "priorities cap 3 -> 2", key: "profileSrc", src: PROFILE_FN,
    find: "priorities.slice(0, 3)", replace: "priorities.slice(0, 2)" },
  // Replaces every `firmness <= 3` in showProfileScreen — the isPlush profile
  // gate, the feel phrase, the feel word AND the preference-priority branch —
  // so it is caught through s2's feel word and s10's profile assignment.
  { name: "plush boundary moved (feel classification + profile + priority)", key: "profileSrc", src: PROFILE_FN,
    find: "firmness <= 3", replace: "firmness <= 4" },
  { name: "accessory ordering reversed", key: "accSrc", src: SCORE_ACC_FN,
    find: "accessoryData.sort((a, b) => b.score - a.score);",
    replace: "accessoryData.sort((a, b) => a.score - b.score);" },
  { name: "accessory matched flag forced on", key: "accSrc", src: SCORE_ACC_FN,
    find: "const matched = reasons.length > 0;", replace: "const matched = true;" },
  // The support sub-type re-sort ({foundation:0, low_profile:1, bunkie:2})
  // deliberately has NO mutation here: the shipped catalog carries exactly one
  // non-adjustable support item, so a single-element sort cannot reorder and
  // any such mutation is uncatchable on this data. The single-item reality is
  // ratcheted in the non-triviality section; when the catalog gains a second
  // support sub-type that check fails and the re-sort mutation must be added.
  // Slice 5 C0: vmSrc was threaded as a mutation key from the start but no
  // entry used it, so nothing proved the view-model extraction was
  // load-bearing. The threshold stamp lives inside getSleepSystemViewModel and
  // is pinned per group item; moving it must diverge.
  // (C3 moved the threshold stamp into readSleepSystemGroups; the mutant
  // keys on that extraction now, proving IT is load-bearing.)
  // 3.7 P3 (2026-08-30): the matched-first pillow rank. Neutralising the
  // comparator restores the pre-P3 order (gel default 2 ahead of the matched
  // Flow for back sleepers) and must diverge from the baseline in s1 / s5.
  { name: "P3 matched-first pillow rank removed", key: "groupsSrc", src: READGROUPS_FN,
    find: "return (b.matched ? 1 : 0) - (a.matched ? 1 : 0);",
    replace: "return 0;" },
  { name: "engine-groups meetsMatchThreshold 0.6 -> 0.9", key: "groupsSrc", src: READGROUPS_FN,
    find: "meetsMatchThreshold: (item.score || 0) >= maxScore * 0.6",
    replace: "meetsMatchThreshold: (item.score || 0) >= maxScore * 0.9" },
  { name: "step partition collapsed (adjustable bases leak into support)", key: "stepSrc", src: STEP_FN,
    find: "return item.subType === 'adjustable' ? 'adjustability' : 'support';",
    replace: "return 'support';" }
];
// Loop non-vacuity (repaired 2026-08-29). From the 2026-08-15 amendment until
// this repair the loop diffed the RAW baseline, whose retained obsolete
// feelWord field diverges from every fresh snapshot, so every mutation
// "diverged" in 10/10 scenarios whatever it changed: the [caught] lines were
// noise. The comparison now applies the same feelWord exclusion section 2
// uses, and the guard below proves the unmutated engine reports ZERO
// divergence on that basis — otherwise the [caught] lines prove nothing.
// All fifteen source mutations still diverge on the repaired basis; their
// real per-scenario counts are printed on each line.
const mutationDiffs = (snap) => {
  const out = [];
  for (const name of Object.keys(SCENARIOS)) {
    out.push(...diffPaths(withoutObsoletePresentation(BASELINE.scenarios[name]), snap.scenarios[name], name));
  }
  return out;
};
const scenariosOf = (diffs) => new Set(diffs.map((d) => d.split(".")[0])).size;
check("the mutation comparison reports zero divergence for the UNMUTATED engine (loop non-vacuity)",
  mutationDiffs(live).length === 0, mutationDiffs(live).slice(0, 3).join(" | "));
for (const mu of MUTATIONS) {
  if (!check(`[applies] ${mu.name}`, mu.src.includes(mu.find), "find-string not in source — stale mutation")) continue;
  const mutated = mu.src.split(mu.find).join(mu.replace);
  const snap = buildSnapshot({ [mu.key]: mutated });
  const divergent = scenariosOf(mutationDiffs(snap));
  check(`[caught] ${mu.name} — ${divergent} scenario(s) diverge`, divergent > 0);
}

// ---------- 5. catalog reason data: exactly the authorized tranche ------------
// Item 1.3 first dark reason tranche (owner-authorized 2026-08-29). The
// per-feature reason strings are catalog DATA, not engine source, so the
// source mutations above cannot see them. These pins prove (a) exactly the
// authorized (model, axis) pairs exist — four from tranche 1 plus eight from
// tranche 2 (2026-08-29) — in both languages, on live scoring tags; (b) the
// pinned baseline carries them in exactly the cells the two bounded
// amendments declared (52 + 86 = 138); and (c) the pin is load-bearing for
// reason data:
// each catalog mutation below edits an in-memory COPY of the catalog, never
// the engine, must diverge at its NAMED matchReasons path, and must diverge
// NOWHERE outside matchReasons (a reason string cannot move a score, rank or
// result — if one ever does, [bounded] fails and that is the finding).
// No mutation may target a case-fold-dead axis (pressureRelief /
// motionIsolation, roadmap 3.1): the engine never reaches those, so such a
// mutation could not be caught and would be a vacuous entry.
section("catalog reason data (item 1.3 tranche): authorized pairs only, and the pin sees them");
// The owner-approved copy, byte for byte (Decision A, 2026-08-29). The fixture
// pins only the ENGLISH strings, because the engine reads `reasons` alone; a
// Spanish sentence could therefore drift through a lineage rebuild and reach
// eventual activation unnoticed. This map pins BOTH languages exactly, and the
// axis view the rest of this section uses is derived from it so the two can
// never disagree. Changing any of these bytes is an owner decision.
const APPROVED_REASON_COPY = {
  s5: { axis: "firm",
    en: "Rated Firm, with less give at the surface and a tight-top construction without a pillow-top layer.",
    es: "Nivel de confort firme, con menos hundimiento en la superficie y una construcción tight top sin capa tipo pillow top." },
  s1: { axis: "support",
    en: "Individually pocketed coils that move independently, zoned for targeted support, with foam encasement around the edge.",
    es: "Resortes embolsados individualmente que se mueven de forma independiente, zonificados para brindar soporte focalizado, con encapsulado de espuma alrededor del borde." },
  b2: { axis: "firm",
    en: "Rated Firm, with less give and more pushback at the surface.",
    es: "Nivel de confort firme, con menos hundimiento y más empuje en la superficie." },
  b7: { axis: "medium",
    en: "Rated Medium — a balanced feel between plush and firm.",
    es: "Nivel de confort medio: una sensación equilibrada entre suave y firme." },
  // Tranche 2 (owner Decision A, 2026-08-29): eight further pairs, byte-exact.
  s4: { axis: "firm",
    en: "Rated Firm, with less give and more pushback at the surface.",
    es: "Nivel de confort firme, con menos hundimiento y más empuje en la superficie." },
  s2: { axis: "firm",
    en: "Rated Extra Firm — a very firm feel with little give at the surface.",
    es: "Nivel de confort extra firme: una sensación muy firme, con poco hundimiento en la superficie." },
  s8: { axis: "firm",
    en: "Rated Firm, with less give and more pushback at the surface.",
    es: "Nivel de confort firme, con menos hundimiento y más empuje en la superficie." },
  s6: { axis: "medium",
    en: "Rated Medium — a balanced feel between plush and firm.",
    es: "Nivel de confort medio: una sensación equilibrada entre suave y firme." },
  s7: { axis: "plush",
    en: "Rated Plush — a softer feel with more give at the surface.",
    es: "Nivel de confort suave: una sensación más suave, con más hundimiento en la superficie." },
  b4: { axis: "firm",
    en: "Rated Firm, with less give and more pushback at the surface.",
    es: "Nivel de confort firme, con menos hundimiento y más empuje en la superficie." },
  b6: { axis: "firm",
    en: "Rated Extra Firm — a very firm feel with little give at the surface.",
    es: "Nivel de confort extra firme: una sensación muy firme, con poco hundimiento en la superficie." },
  b5: { axis: "plush",
    en: "Rated Plush — a softer feel with more give at the surface.",
    es: "Nivel de confort suave: una sensación más suave, con más hundimiento en la superficie." }
};
const AUTHORIZED_REASONS = Object.fromEntries(
  Object.entries(APPROVED_REASON_COPY).map(([id, c]) => [id, c.axis]));
const findIn = (cat, id) => Object.values(cat).flat().find((m) => m.id === id);
const byId = (id) => findIn(MATTRESSES, id);
// Reusable comparator: every authorized model id, axis, `reasons[axis]` and
// `reasons_es[axis]` against the map, exact string equality, returning named
// mismatches ("<id>.<axis>.<lang>"). The live assertion and the negative
// controls below run this same function.
function reasonCopyMismatches(cat) {
  const out = [];
  for (const [id, exp] of Object.entries(APPROVED_REASON_COPY)) {
    const m = findIn(cat, id);
    if (!m) { out.push(`${id}: model missing`); continue; }
    const got = { en: (m.reasons || {})[exp.axis], es: (m.reasons_es || {})[exp.axis] };
    for (const lang of ["en", "es"]) {
      if (got[lang] !== exp[lang]) {
        out.push(`${id}.${exp.axis}.${lang}: ${JSON.stringify(got[lang])} != ${JSON.stringify(exp[lang])}`);
      }
    }
  }
  return out;
}
const perFeatureKeys = (obj) => Object.keys(obj || {}).filter((k) => k !== "default").sort();
{
  const all = Object.values(MATTRESSES).flat();
  const populated = all.filter((m) => perFeatureKeys(m.reasons).length)
    .map((m) => `${m.id}.${perFeatureKeys(m.reasons).join("+")}`).sort();
  check("exactly the twelve authorized (model, axis) per-feature reasons exist in `reasons` (tranche 1: b2.firm, b7.medium, s1.support, s5.firm; tranche 2: b4.firm, b5.plush, b6.firm, s2.firm, s4.firm, s6.medium, s7.plush, s8.firm)",
    JSON.stringify(populated) === JSON.stringify(["b2.firm", "b4.firm", "b5.plush", "b6.firm", "b7.medium", "s1.support", "s2.firm", "s4.firm", "s5.firm", "s6.medium", "s7.plush", "s8.firm"]), populated.join(", "));
  check("the authorized set in the map is exactly those twelve (map and catalog agree)",
    JSON.stringify(Object.entries(AUTHORIZED_REASONS).map(([id, a]) => `${id}.${a}`).sort()) === JSON.stringify(populated));
  check("reasons_es carries exactly the same per-feature (model, axis) key set as reasons on every model",
    all.every((m) => JSON.stringify(perFeatureKeys(m.reasons)) === JSON.stringify(perFeatureKeys(m.reasons_es))),
    all.filter((m) => JSON.stringify(perFeatureKeys(m.reasons)) !== JSON.stringify(perFeatureKeys(m.reasons_es))).map((m) => m.id).join(", "));
  {
    const mism = reasonCopyMismatches(MATTRESSES);
    check("every authorized (model, axis) carries EXACTLY the owner-approved EN and ES bytes (APPROVED_REASON_COPY)",
      mism.length === 0, mism.join(" | "));
  }
  // Secondary to the exact-copy pin above: documents that every approved
  // sentence is full-stop terminated, which is what data mutation M3 removes.
  check("(secondary) every approved EN/ES sentence in the map ends with a full stop",
    Object.values(APPROVED_REASON_COPY).every((c) => /\.$/.test(c.en) && /\.$/.test(c.es)));
  check("every authorized axis is a live scoring tag on its model (not a case-fold-dead slot)",
    Object.entries(AUTHORIZED_REASONS).every(([id, axis]) => byId(id).features.includes(axis)));
  let cells = 0, esCellsHoldEnglish = 0;
  const reach = Object.fromEntries(Object.keys(AUTHORIZED_REASONS).map((id) => [id, []]));
  for (const [name, s] of Object.entries(BASELINE.scenarios)) {
    for (const [id, axis] of Object.entries(AUTHORIZED_REASONS)) {
      if (s.matchReasons.en[id].includes(byId(id).reasons[axis])) { cells++; reach[id].push(name); }
      if (s.matchReasons.es[id].includes(byId(id).reasons[axis])) { cells++; esCellsHoldEnglish++; }
    }
  }
  check("the pinned baseline carries the two tranches in exactly 138 matchReasons cells (69 EN + 69 ES; tranche 1 = 52, tranche 2 = 86)", cells === 138, String(cells));
  check("the 69 ES cells hold the ENGLISH string (no Spanish reason reader exists; recorded, not approved)",
    esCellsHoldEnglish === 69, String(esCellsHoldEnglish));
  const T1_CELLS = (reach.s1.length + reach.s5.length + reach.b2.length + reach.b7.length) * 2;
  check("tranche-1 cells are still exactly 52 (its reach did not move: s1.support 8, b7.medium 8, s5.firm 5, b2.firm 5)",
    T1_CELLS === 52 && reach.s1.length === 8 && reach.b7.length === 8 && reach.s5.length === 5 && reach.b2.length === 5, String(T1_CELLS));
  check("per-model reach: tranche 1 as above; tranche 2 s6.medium 8, s4/s2/s8/b4/b6.firm 5 each, s7/b5.plush 5 each; s9_empty_defaults carries none",
    reach.s1.length === 8 && reach.b7.length === 8 && reach.s5.length === 5 && reach.b2.length === 5
    && reach.s6.length === 8 && reach.s4.length === 5 && reach.s2.length === 5 && reach.s8.length === 5
    && reach.b4.length === 5 && reach.b6.length === 5 && reach.s7.length === 5 && reach.b5.length === 5
    && !Object.values(reach).flat().includes("s9_empty_defaults"),
    JSON.stringify(Object.fromEntries(Object.entries(reach).map(([k, v]) => [k, v.length]))));
}
// Negative controls for the exact-copy contract. reasons_es has no runtime
// reader, so an ES drift can NEVER surface through buildSnapshot()/the fixture;
// these controls run the comparator itself on an in-memory catalog clone and
// require a failure naming the expected model, axis and language. Every
// approved translation is controlled individually, two ways (terminal full
// stop removed; one character changed), plus one EN control proving the
// comparator covers both languages. Nothing is written to disk: the source
// bytes of data/mattresses.json and the loaded MATTRESSES object are proven
// unchanged afterwards.
section("exact-copy contract: negative controls (ES drift is caught without a runtime reader)");
{
  const catalogPath = join(root, "data", "mattresses.json");
  const diskBefore = createHash("sha256").update(readFileSync(catalogPath)).digest("hex");
  const memBefore = JSON.stringify(MATTRESSES);
  const controls = [];
  for (const [id, exp] of Object.entries(APPROVED_REASON_COPY)) {
    controls.push({ id, lang: "es", name: `${id}.${exp.axis}.es terminal full stop removed`,
      mutate: (v) => v.replace(/\.$/, "") });
    controls.push({ id, lang: "es", name: `${id}.${exp.axis}.es one character changed`,
      mutate: (v) => v.slice(0, 5) + (v[5] === "x" ? "y" : "x") + v.slice(6) });
  }
  controls.push({ id: "s5", lang: "en", name: "s5.firm.en one character changed (comparator covers EN too)",
    mutate: (v) => v.slice(0, 5) + (v[5] === "x" ? "y" : "x") + v.slice(6) });
  for (const c of controls) {
    const exp = APPROVED_REASON_COPY[c.id];
    const cat = clone(MATTRESSES);
    const m = findIn(cat, c.id);
    const field = c.lang === "es" ? "reasons_es" : "reasons";
    const before = m[field][exp.axis];
    m[field][exp.axis] = c.mutate(before);
    if (!check(`[applies] ${c.name}`, m[field][exp.axis] !== before, "mutation produced no change")) continue;
    const mism = reasonCopyMismatches(cat);
    const expected = `${c.id}.${exp.axis}.${c.lang}: `;
    check(`[caught] ${c.name} — exactly one mismatch, naming ${expected.trim()}`,
      mism.length === 1 && mism[0].startsWith(expected), mism.join(" | "));
  }
  check("negative controls touched no disk artifact (data/mattresses.json bytes unchanged)",
    createHash("sha256").update(readFileSync(catalogPath)).digest("hex") === diskBefore);
  check("negative controls left the loaded catalog untouched (mutations were on clones)",
    JSON.stringify(MATTRESSES) === memBefore && reasonCopyMismatches(MATTRESSES).length === 0);
}
const DATA_MUTATIONS = [
  { name: "M1 unauthorized model outside the approved set (g1.reasons.support added)",
    at: /^[^.]+\.matchReasons\.(en|es)\.g1\.length: /,
    apply(cat) {
      const m = findIn(cat, "g1");
      if (!m) return "g1 missing";
      if (m.reasons && "support" in m.reasons) return "g1 already carries a support reason";
      if (!m.features.includes("support")) return "g1 has no live support tag";
      m.reasons = { ...(m.reasons || {}), support: "UNAUTHORIZED REASON" };
      return "applied";
    } },
  { name: "M2 unauthorized second axis (s1.reasons.firm added)",
    at: /^[^.]+\.matchReasons\.(en|es)\.s1\.length: /,
    apply(cat) {
      const m = findIn(cat, "s1");
      if ("firm" in m.reasons) return "s1 already carries a firm reason";
      if (!m.features.includes("firm")) return "s1 has no live firm tag";
      m.reasons = { ...m.reasons, firm: "UNAUTHORIZED REASON" };
      return "applied";
    } },
  { name: "M3 approved-string drift (s5.reasons.firm loses its terminal full stop)",
    at: /^[^.]+\.matchReasons\.(en|es)\.s5\[\d+\]: /,
    apply(cat) {
      const m = findIn(cat, "s5");
      if (!m.reasons.firm || !m.reasons.firm.endsWith(".")) return "s5.reasons.firm missing or already without a full stop";
      m.reasons.firm = m.reasons.firm.slice(0, -1);
      return "applied";
    } },
  { name: "M4 tranche removal (b7.reasons.medium deleted)",
    at: /^[^.]+\.matchReasons\.(en|es)\.b7\.length: /,
    apply(cat) {
      const m = findIn(cat, "b7");
      if (!("medium" in m.reasons)) return "b7.reasons.medium missing";
      delete m.reasons.medium;
      return "applied";
    } },
  // Tranche 2 (2026-08-29): one removal mutation per newly populated slot, so
  // each of the eight is individually pinned by the fixture; plus an
  // unauthorized second axis on a tranche-2 model, an unauthorized thirteenth
  // model, and a string-drift control on the new Extra Firm sentence class.
  ...Object.entries({ s4: "firm", s2: "firm", s8: "firm", s6: "medium", s7: "plush", b4: "firm", b6: "firm", b5: "plush" })
    .map(([id, axis]) => ({
      name: `T2 tranche removal (${id}.reasons.${axis} deleted)`,
      at: new RegExp(`^[^.]+\\.matchReasons\\.(en|es)\\.${id}\\.length: `),
      apply(cat) {
        const m = findIn(cat, id);
        if (!(axis in m.reasons)) return `${id}.reasons.${axis} missing`;
        delete m.reasons[axis];
        return "applied";
      } })),
  { name: "M5 unauthorized second axis on a tranche-2 model (s6.reasons.support added)",
    at: /^[^.]+\.matchReasons\.(en|es)\.s6\.length: /,
    apply(cat) {
      const m = findIn(cat, "s6");
      if ("support" in m.reasons) return "s6 already carries a support reason";
      if (!m.features.includes("support")) return "s6 has no live support tag";
      m.reasons = { ...m.reasons, support: "UNAUTHORIZED REASON" };
      return "applied";
    } },
  { name: "M6 unauthorized thirteenth model (s9.reasons.medium added)",
    at: /^[^.]+\.matchReasons\.(en|es)\.s9\.length: /,
    apply(cat) {
      const m = findIn(cat, "s9");
      if (m.reasons && "medium" in m.reasons) return "s9 already carries a medium reason";
      if (!m.features.includes("medium")) return "s9 has no live medium tag";
      m.reasons = { ...(m.reasons || {}), medium: "UNAUTHORIZED REASON" };
      return "applied";
    } },
  { name: "M7 approved-string drift on the Extra Firm sentence (s2.reasons.firm loses its terminal full stop)",
    at: /^[^.]+\.matchReasons\.(en|es)\.s2\[\d+\]: /,
    apply(cat) {
      const m = findIn(cat, "s2");
      if (!m.reasons.firm || !m.reasons.firm.endsWith(".")) return "s2.reasons.firm missing or already without a full stop";
      m.reasons.firm = m.reasons.firm.slice(0, -1);
      return "applied";
    } }
];
for (const mu of DATA_MUTATIONS) {
  const cat = clone(MATTRESSES);
  const status = mu.apply(cat);
  if (!check(`[applies] ${mu.name}`, status === "applied", status)) continue;
  const diffs = mutationDiffs(buildSnapshot({ mattresses: cat }));
  const named = diffs.filter((d) => mu.at.test(d));
  const outside = diffs.filter((d) => !/\.matchReasons\./.test(d));
  check(`[caught] ${mu.name} — ${scenariosOf(diffs)} scenario(s) diverge, ${named.length} at the named path`,
    diffs.length > 0 && named.length > 0, diffs.slice(0, 3).join(" | "));
  check(`[bounded] ${mu.name} — no divergence outside matchReasons`, outside.length === 0, outside.slice(0, 3).join(" | "));
}

console.log(`\nPhase 1 output regression check: ${passed} passed, ${failed} failed`);
process.exit(failed ? 1 : 0);
